export type GlobalRole = 'ADMIN' | 'SHOPKEEPER' | 'SHOPPER';

export type BusinessRole = 
  | 'OWNER' 
  | 'MANAGER' 
  | 'CASHIER' 
  | 'SALESPERSON' 
  | 'ACCOUNTANT' 
  | 'INVENTORY_MANAGER';

export const PERMISSIONS = {
  // Business Management
  BUSINESS_READ: 'business.read',
  BUSINESS_UPDATE: 'business.update',
  BUSINESS_DELETE: 'business.delete',
  
  // Customers & Ledgers
  CUSTOMER_READ: 'customer.read',
  CUSTOMER_CREATE: 'customer.create',
  CUSTOMER_UPDATE: 'customer.update',
  CUSTOMER_DELETE: 'customer.delete',
  
  // Khata Transactions
  TRANSACTION_READ: 'transaction.read',
  TRANSACTION_CREATE: 'transaction.create',
  TRANSACTION_REVERSE: 'transaction.reverse',
  
  // Invoicing & POS
  INVOICE_READ: 'invoice.read',
  INVOICE_CREATE: 'invoice.create',
  INVOICE_UPDATE: 'invoice.update',
  INVOICE_CANCEL: 'invoice.cancel',

  // Payments
  PAYMENT_READ: 'payment.read',
  PAYMENT_CREATE: 'payment.create',
  
  // Inventory & Stock
  INVENTORY_READ: 'inventory.read',
  INVENTORY_CREATE: 'inventory.create',
  INVENTORY_UPDATE: 'inventory.update',
  INVENTORY_ADJUST: 'inventory.adjust',
  
  // Suppliers
  SUPPLIER_READ: 'supplier.read',
  SUPPLIER_CREATE: 'supplier.create',
  SUPPLIER_UPDATE: 'supplier.update',
  
  // Expenses
  EXPENSE_READ: 'expense.read',
  EXPENSE_CREATE: 'expense.create',
  EXPENSE_UPDATE: 'expense.update',
  
  // Reports
  REPORT_READ: 'report.read',
  
  // Staff & Members
  STAFF_READ: 'staff.read',
  STAFF_INVITE: 'staff.invite',
  STAFF_UPDATE: 'staff.update',
  STAFF_REMOVE: 'staff.remove',

  // Settings
  SETTINGS_READ: 'settings.read',
  SETTINGS_UPDATE: 'settings.update',
  
  // AI
  AI_QUERY: 'ai.query',
  
  // Shopper Consumer Permissions
  SHOPPER_PURCHASES_READ: 'shopper.purchases.read',
  SHOPPER_KHATA_READ: 'shopper.khata.read',
  SHOPPER_TRANSACTION_ACK: 'shopper.transaction.ack',
  SHOPPER_TRANSACTION_DISPUTE: 'shopper.transaction.dispute',
  
  // Platform Admin Permissions
  PLATFORM_USERS_READ: 'platform.users.read',
  PLATFORM_USERS_MANAGE: 'platform.users.manage',
  PLATFORM_BUSINESSES_READ: 'platform.businesses.read',
  PLATFORM_BUSINESSES_MANAGE: 'platform.businesses.manage',
  PLATFORM_SUBSCRIPTIONS_MANAGE: 'platform.subscriptions.manage',
  PLATFORM_AUDIT_READ: 'platform.audit.read',
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS: Record<BusinessRole, PermissionKey[]> = {
  OWNER: [
    PERMISSIONS.BUSINESS_READ,
    PERMISSIONS.BUSINESS_UPDATE,
    PERMISSIONS.BUSINESS_DELETE,
    PERMISSIONS.CUSTOMER_READ,
    PERMISSIONS.CUSTOMER_CREATE,
    PERMISSIONS.CUSTOMER_UPDATE,
    PERMISSIONS.CUSTOMER_DELETE,
    PERMISSIONS.TRANSACTION_READ,
    PERMISSIONS.TRANSACTION_CREATE,
    PERMISSIONS.TRANSACTION_REVERSE,
    PERMISSIONS.INVOICE_READ,
    PERMISSIONS.INVOICE_CREATE,
    PERMISSIONS.INVOICE_UPDATE,
    PERMISSIONS.INVOICE_CANCEL,
    PERMISSIONS.PAYMENT_READ,
    PERMISSIONS.PAYMENT_CREATE,
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.INVENTORY_CREATE,
    PERMISSIONS.INVENTORY_UPDATE,
    PERMISSIONS.INVENTORY_ADJUST,
    PERMISSIONS.SUPPLIER_READ,
    PERMISSIONS.SUPPLIER_CREATE,
    PERMISSIONS.SUPPLIER_UPDATE,
    PERMISSIONS.EXPENSE_READ,
    PERMISSIONS.EXPENSE_CREATE,
    PERMISSIONS.EXPENSE_UPDATE,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.STAFF_READ,
    PERMISSIONS.STAFF_INVITE,
    PERMISSIONS.STAFF_UPDATE,
    PERMISSIONS.STAFF_REMOVE,
    PERMISSIONS.SETTINGS_READ,
    PERMISSIONS.SETTINGS_UPDATE,
    PERMISSIONS.AI_QUERY,
  ],
  MANAGER: [
    PERMISSIONS.BUSINESS_READ,
    PERMISSIONS.BUSINESS_UPDATE,
    PERMISSIONS.CUSTOMER_READ,
    PERMISSIONS.CUSTOMER_CREATE,
    PERMISSIONS.CUSTOMER_UPDATE,
    PERMISSIONS.TRANSACTION_READ,
    PERMISSIONS.TRANSACTION_CREATE,
    PERMISSIONS.TRANSACTION_REVERSE,
    PERMISSIONS.INVOICE_READ,
    PERMISSIONS.INVOICE_CREATE,
    PERMISSIONS.INVOICE_UPDATE,
    PERMISSIONS.PAYMENT_READ,
    PERMISSIONS.PAYMENT_CREATE,
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.INVENTORY_CREATE,
    PERMISSIONS.INVENTORY_UPDATE,
    PERMISSIONS.INVENTORY_ADJUST,
    PERMISSIONS.SUPPLIER_READ,
    PERMISSIONS.SUPPLIER_CREATE,
    PERMISSIONS.SUPPLIER_UPDATE,
    PERMISSIONS.EXPENSE_READ,
    PERMISSIONS.EXPENSE_CREATE,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.STAFF_READ,
    PERMISSIONS.STAFF_INVITE,
    PERMISSIONS.SETTINGS_READ,
    PERMISSIONS.AI_QUERY,
  ],
  CASHIER: [
    PERMISSIONS.BUSINESS_READ,
    PERMISSIONS.CUSTOMER_READ,
    PERMISSIONS.CUSTOMER_CREATE,
    PERMISSIONS.TRANSACTION_READ,
    PERMISSIONS.TRANSACTION_CREATE,
    PERMISSIONS.INVOICE_READ,
    PERMISSIONS.INVOICE_CREATE,
    PERMISSIONS.PAYMENT_READ,
    PERMISSIONS.PAYMENT_CREATE,
    PERMISSIONS.INVENTORY_READ,
  ],
  SALESPERSON: [
    PERMISSIONS.BUSINESS_READ,
    PERMISSIONS.CUSTOMER_READ,
    PERMISSIONS.CUSTOMER_CREATE,
    PERMISSIONS.INVOICE_READ,
    PERMISSIONS.INVOICE_CREATE,
    PERMISSIONS.INVENTORY_READ,
  ],
  ACCOUNTANT: [
    PERMISSIONS.BUSINESS_READ,
    PERMISSIONS.CUSTOMER_READ,
    PERMISSIONS.TRANSACTION_READ,
    PERMISSIONS.INVOICE_READ,
    PERMISSIONS.PAYMENT_READ,
    PERMISSIONS.EXPENSE_READ,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.SUPPLIER_READ,
  ],
  INVENTORY_MANAGER: [
    PERMISSIONS.BUSINESS_READ,
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.INVENTORY_CREATE,
    PERMISSIONS.INVENTORY_UPDATE,
    PERMISSIONS.INVENTORY_ADJUST,
    PERMISSIONS.SUPPLIER_READ,
    PERMISSIONS.SUPPLIER_CREATE,
  ],
};

export function hasPermission(
  role: BusinessRole | string,
  permission: PermissionKey
): boolean {
  const roleKey = role as BusinessRole;
  const permissions = ROLE_PERMISSIONS[roleKey];
  if (!permissions) return false;
  return permissions.includes(permission);
}
